// Stores with publicly readable Shopify catalogs (verified via /products.json).
// Each one is effectively a free product API: title, price, images, tags, URL.

export type Source = {
  id: string;
  name: string;
  domain: string;
  vibe: string;
};

export const SOURCES: Source[] = [
  { id: "everlane", name: "Everlane", domain: "everlane.com", vibe: "modern minimalist basics, denim, workwear staples; men + women; mid-range" },
  { id: "jennikayne", name: "Jenni Kayne", domain: "jennikayne.com", vibe: "quiet luxury, coastal California, cashmere and neutrals; premium" },
  { id: "doen", name: "DÔEN", domain: "shopdoen.com", vibe: "romantic vintage-inspired California dresses and blouses; premium" },
  { id: "rails", name: "Rails", domain: "railsclothing.com", vibe: "elevated casual, silky shirting, effortless LA style; contemporary" },
  { id: "staud", name: "STAUD", domain: "staud.clothing", vibe: "modern feminine, sculptural silhouettes, statement pieces; contemporary" },
  { id: "frankandeileen", name: "Frank & Eileen", domain: "frankandeileen.com", vibe: "heritage Irish shirting, oversized button-downs; premium" },
  { id: "nakedcashmere", name: "NAKED Cashmere", domain: "nakedcashmere.com", vibe: "pure cashmere knits and loungewear; premium" },
  { id: "agolde", name: "AGOLDE", domain: "agolde.com", vibe: "premium LA denim, vintage-inspired fits" },
  { id: "goodamerican", name: "Good American", domain: "goodamerican.com", vibe: "size-inclusive denim and bodycon basics; mid-range" },
  { id: "aloyoga", name: "Alo Yoga", domain: "aloyoga.com", vibe: "athleisure, studio-to-street activewear; mid-range" },
  { id: "marinelayer", name: "Marine Layer", domain: "marinelayer.com", vibe: "soft casual basics, coastal weekend wear; men + women; mid-range" },
  { id: "faherty", name: "Faherty", domain: "fahertybrand.com", vibe: "coastal casual, sweaters and linen; men + women; mid-premium" },
  { id: "oakandfort", name: "Oak + Fort", domain: "oakandfort.com", vibe: "clean minimalist essentials, muted palette; men + women; mid-range" },
  { id: "colorfulstandard", name: "Colorful Standard", domain: "colorfulstandard.com", vibe: "organic cotton basics in every color; men + women; affordable" },
  { id: "christydawn", name: "Christy Dawn", domain: "christydawn.com", vibe: "romantic sustainable prairie dresses; premium" },
  { id: "withjean", name: "With Jéan", domain: "withjean.com", vibe: "feminine going-out pieces, mini dresses; contemporary" },
  { id: "meshki", name: "MESHKI", domain: "meshki.us", vibe: "sleek minimal going-out, satin and knits; mid-range" },
  { id: "ohpolly", name: "Oh Polly", domain: "ohpolly.com", vibe: "bodycon occasion and event dresses; mid-range" },
  { id: "showmeyourmumu", name: "Show Me Your Mumu", domain: "showmeyourmumu.com", vibe: "boho party and bridesmaid, playful prints; mid-range" },
  { id: "petalandpup", name: "Petal & Pup", domain: "petalandpup.com", vibe: "feminine dresses and workwear; affordable-mid" },
  { id: "princesspolly", name: "Princess Polly", domain: "us.princesspolly.com", vibe: "trendy Gen-Z going-out and casual; affordable" },
  { id: "vici", name: "VICI", domain: "vicicollection.com", vibe: "trendy boutique, layered looks; affordable-mid" },
  { id: "pinklily", name: "Pink Lily", domain: "pinklily.com", vibe: "sweet Southern boutique style; affordable" },
  { id: "fashionnova", name: "Fashion Nova", domain: "fashionnova.com", vibe: "fast-fashion trendy, curve-friendly; budget" },
  { id: "cupshe", name: "Cupshe", domain: "cupshe.com", vibe: "swim and resort wear; budget" },
  // ——— activewear / gym ———
  { id: "gymshark", name: "Gymshark", domain: "gymshark.com", vibe: "performance gym wear, seamless leggings and lifting sets; men + women; mid-range" },
  { id: "aybl", name: "AYBL", domain: "www.aybl.com", vibe: "sculpting seamless gym sets, squat-proof leggings; women; affordable-mid" },
  { id: "nvgtn", name: "NVGTN", domain: "nvgtn.com", vibe: "contour seamless leggings and scrunch shorts, gym-influencer staple; women" },
  { id: "setactive", name: "Set Active", domain: "setactive.co", vibe: "matching athleisure sets in muted earth tones, LA studio-to-street; women" },
  { id: "dfyne", name: "DFYNE", domain: "dfyne.com", vibe: "high-impact sculpting activewear, bold and refined; women; mid-range" },
  { id: "buffbunny", name: "Buffbunny", domain: "buffbunny.com", vibe: "feminine lifting wear, supportive and curve-focused; women" },
  { id: "vitality", name: "Vitality", domain: "vitalityathletic.com", vibe: "buttery cloud-soft leggings and flares, wellness aesthetic; women" },
  { id: "bornprimitive", name: "Born Primitive", domain: "bornprimitive.com", vibe: "training and crossfit wear, durable and patriotic-lean; men + women" },
  { id: "boandtee", name: "Bo+Tee", domain: "boandtee.com", vibe: "trendy gym-to-brunch sets and one-shoulder tops; women; affordable" },
  { id: "youngla", name: "YoungLA", domain: "youngla.com", vibe: "bodybuilding and streetwear-lean gym fits, pump covers; mostly men" },
  { id: "tenthousand", name: "Ten Thousand", domain: "tenthousand.cc", vibe: "minimal high-performance men's training gear; men; mid-premium" },
  { id: "outdoorvoices", name: "Outdoor Voices", domain: "outdoorvoices.com", vibe: "recreational athleisure, playful color-block, doing-things energy; men + women" },
  { id: "girlfriend", name: "Girlfriend Collective", domain: "girlfriend.com", vibe: "sustainable compressive activewear in rich muted colors, size-inclusive; women" },
  { id: "beyondyoga", name: "Beyond Yoga", domain: "beyondyoga.com", vibe: "buttery spacedye yoga and lounge wear; women; mid-premium" },
  // ——— European / old money / quiet luxury ———
  { id: "toteme", name: "Toteme", domain: "toteme-studio.com", vibe: "Scandinavian quiet luxury, impeccable tailoring, the old-money uniform; luxury (EUR prices)" },
  { id: "frankieshop", name: "The Frankie Shop", domain: "thefrankieshop.com", vibe: "oversized blazers, sharp Parisian-NY minimalism; contemporary" },
  { id: "rouje", name: "Rouje", domain: "rouje.com", vibe: "Parisian it-girl, wrap dresses and silk blouses, Jeanne Damas French chic (EUR prices)" },
  { id: "musier", name: "Musier Paris", domain: "musier-paris.com", vibe: "playful Parisian, knit sets and scarf tops (EUR prices)" },
  { id: "soeur", name: "Soeur", domain: "soeur.fr", vibe: "understated French bourgeois elegance, refined basics; premium (EUR prices)" },
  { id: "balzac", name: "Balzac Paris", domain: "balzac-paris.fr", vibe: "responsible Parisian wardrobe, feminine and timeless (EUR prices)" },
  { id: "stagni", name: "St. Agni", domain: "st-agni.com", vibe: "minimalist old-money resort, linen tailoring and leather; premium" },
  { id: "matteau", name: "Matteau", domain: "matteau-store.com", vibe: "refined Riviera resortwear, elegant swim and linen; premium" },
  { id: "posse", name: "Posse", domain: "posse.com", vibe: "European-summer linen sets, effortless vacation tailoring; contemporary" },
  { id: "dissh", name: "DISSH", domain: "dissh.com", vibe: "clean linen and neutral resort tailoring, Euro-summer staple; mid-range" },
  { id: "favoritedaughter", name: "Favorite Daughter", domain: "favoritedaughter.com", vibe: "polished old-money blazers and trousers with a wink; contemporary" },
  { id: "aligne", name: "ALIGNE", domain: "aligne.co", vibe: "elevated UK tailoring, structured blazers and dresses; mid-range" },
  { id: "omnes", name: "OMNES", domain: "omnes.com", vibe: "sustainable UK occasion and workwear, quietly chic; affordable-mid" },
  { id: "nobodyschild", name: "Nobody's Child", domain: "nobodyschild.com", vibe: "feminine UK high-street dresses, ditsy prints; affordable" },
  { id: "damsonmadder", name: "Damson Madder", domain: "damsonmadder.com", vibe: "playful London vintage-inspired, ruffles and checks; mid-range" },
  { id: "lisasaysgah", name: "Lisa Says Gah", domain: "lisasaysgah.com", vibe: "eclectic European-flea-market color and print; contemporary" },
  { id: "ciaolucia", name: "Ciao Lucia", domain: "ciaolucia.com", vibe: "Italian-holiday knit tops and slinky resort dresses; contemporary" },
  { id: "astr", name: "ASTR the Label", domain: "astrthelabel.com", vibe: "feminine event and vacation dresses, polished date-night; mid-range" },
  { id: "sir", name: "SIR.", domain: "sirthelabel.com", vibe: "sculptural Australian minimalism, silk and linen Euro-summer; premium" },
  { id: "faithfull", name: "Faithfull the Brand", domain: "faithfullthebrand.com", vibe: "Mediterranean-holiday linen dresses and sets; contemporary" },
  // ——— workwear / office ———
  { id: "mmlafleur", name: "M.M.LaFleur", domain: "mmlafleur.com", vibe: "polished women's workwear, machine-washable suiting and sheath dresses; premium" },
  { id: "argent", name: "Argent", domain: "argentwork.com", vibe: "power suiting for women, bold blazers and tailored trousers; premium" },
  { id: "ministryofsupply", name: "Ministry of Supply", domain: "ministryofsupply.com", vibe: "performance-fabric office wear, wrinkle-free tailoring; men + women; mid-premium" },
  { id: "priceless", name: "Shop Priceless", domain: "shoppriceless.com", vibe: "budget-friendly trendy boutique, office-casual sets; budget" },
  // ——— streetwear / casual street style ———
  { id: "edikted", name: "Edikted", domain: "edikted.com", vibe: "Gen-Z street style, baggy jeans, cargos, crop tops; budget-mid" },
  { id: "motelrocks", name: "Motel Rocks", domain: "motelrocks.com", vibe: "Y2K and indie-sleaze going-out street style; mid-range" },
  { id: "raggedpriest", name: "The Ragged Priest", domain: "theraggedpriest.com", vibe: "London grunge streetwear, statement denim; mid-range" },
  { id: "mingalondon", name: "Minga London", domain: "mingalondon.com", vibe: "playful UK streetwear, graphic knits and baggy fits; mid-range" },
  { id: "dailypaper", name: "Daily Paper", domain: "dailypaperclothing.com", vibe: "Amsterdam streetwear, elevated graphics; men + women; mid-premium" },
  { id: "stussy", name: "Stüssy", domain: "stussy.com", vibe: "iconic skate-surf streetwear, jerseys and workwear jackets; men + women" },
  { id: "obey", name: "Obey", domain: "obeyclothing.com", vibe: "graphic street and workwear heritage; men + women; mid-range" },
  { id: "brandymelville", name: "Brandy Melville", domain: "us.brandymelville.com", vibe: "effortless casual basics, tanks and slouchy knits; budget" },
  { id: "sistersandseekers", name: "Sisters & Seekers", domain: "sistersandseekers.com", vibe: "UK oversized streetwear sets, neutral tones; mid-range" },
  { id: "adanola", name: "Adanola", domain: "adanola.com", vibe: "minimal athleisure-street uniform, hoodies and leggings; mid-range" },
  { id: "kith", name: "Kith", domain: "kith.com", vibe: "NYC luxury streetwear, elevated fleece and sneakers-adjacent; men + women; premium" },
  { id: "aelfriceden", name: "Aelfric Eden", domain: "aelfriceden.com", vibe: "graphic vintage-wash streetwear, unisex baggy fits; budget-mid" },
  { id: "peppermayo", name: "Peppermayo", domain: "peppermayo.com", vibe: "Aussie it-girl street and going-out; mid-range" },
  { id: "whitefox", name: "White Fox", domain: "whitefoxboutique.com", vibe: "oversized hoodie sets and street-casual; mid-range" },
  { id: "lioness", name: "Lioness", domain: "lionessfashion.com", vibe: "edgy tailored street style, corp-core minis; affordable-mid" },
  // ——— comfort / lounge ———
  { id: "lounge", name: "Lounge", domain: "loungeunderwear.com", vibe: "soft ribbed lounge sets and intimates; mid-range" },
  { id: "eberjey", name: "Eberjey", domain: "eberjey.com", vibe: "the softest pajama sets, elevated sleepwear; premium" },
  { id: "barefootdreams", name: "Barefoot Dreams", domain: "barefootdreams.com", vibe: "famously cozy CozyChic knits, cardigans and blankets-you-wear; mid-premium" },
  { id: "lunya", name: "Lunya", domain: "lunya.co", vibe: "washable silk and pima sleepwear, refined lounge; premium" },
  { id: "aviatornation", name: "Aviator Nation", domain: "aviatornation.com", vibe: "retro 70s California sweats and hoodies, rainbow stripes; premium" },
  { id: "richerpoorer", name: "Richer Poorer", domain: "richer-poorer.com", vibe: "elevated everyday sweats and tees, muted tones; mid-range" },
  { id: "splendid", name: "Splendid", domain: "splendid.com", vibe: "buttery-soft everyday knits and lounge; mid-range" },
  { id: "krushkandy", name: "Krush Kandy", domain: "krushkandy.com", vibe: "cozy boutique hoodie-and-short sets, warm tones; affordable" },
  { id: "jluxlabel", name: "JLUXLABEL", domain: "jluxlabel.com", vibe: "chic comfort sets, knit co-ords and resort glam; mid-range" },
];

export const sourceById = (id: string) => SOURCES.find((s) => s.id === id);
